symbols:
    crypto:
        - symbol: BTCUSDT
          exchange: binance
          enabled: true
        - symbol: ETHUSDT
          exchange: binance
          enabled: true
    stocks:
        - symbol: TSLA
          exchange: nasdaq
          enabled: true
        - symbol: PLTR
          exchange: nasdaq
          enabled: true
    indices:
        - symbol: "^VIX"
          exchange: cboe
          enabled: true
timeframes:
    - 1W
    - 1D
    - 4H
    - 1H
    - 15M
